#
# ---------------------------------------------------------------------
#
# GLPI - Gestionnaire Libre de Parc Informatique
#
# http://glpi-project.org
#
# @copyright 2015-2024 Teclib' and contributors.
# @copyright 2003-2014 by the INDEPNET Development Team.
# @licence   https://www.gnu.org/licenses/gpl-3.0.html
#
# ---------------------------------------------------------------------
#
# LICENSE
#
# This file is part of GLPI.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# ---------------------------------------------------------------------
#

name: 'Close stale issues'
on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  stale:
    if: github.repository == 'glpi-plugin/pdf'
    permissions:
      issues: write  # for actions/stale to close stale issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: >-
            There has been no activity on this issue for some time and therefore it is considered stale
            and will be closed automatically in 10 days.
            
            
            If this issue is related to a bug, please try to reproduce on latest release. If the problem persist,
            feel free to add a comment to revive this issue.
            
            If it is related to a new feature, please open a topic to discuss with community about this enhancement
            on [suggestion website](https://glpi.userecho.com/).
            
            
            You may also consider taking a [subscription](https://glpi-project.org/subscriptions/) to get professionnal
            support or [contact GLPI editor team](https://portal.glpi-network.com/contact-us) directly.
          days-before-issue-stale: 15
          days-before-pr-stale: -1 # PR will be marked as stale manually.
          days-before-close: 5
          exempt-issue-labels: "bug,enhancement,question,security" # Issues with "bug", "enhancement", "question" or "security" labels will not be marked as stale
          exempt-all-milestones: true # Do not check issues/PR with defined milestone.
          ascending: true # First check older issues/PR.
          operations-per-run: 750 # Max API calls per run.
